// SYSTEM emojis only: bare Unicode codepoints, drawn by the visitor's own platform font
// — Apple Color Emoji, Segoe UI Emoji, Noto. Nothing is shipped and nothing is fetched,
// so what a reader sees here is what their own machine will put in the message they paste
// it into. That is the point of the page: not a picture of an emoji, but the emoji.
//
// A curated cross-section and not the whole ~1900-strong set. 772 of them, across nine
// groups, each carrying a name so the search has something to match. Tuples rather than
// objects, because 772 of `{ char, name }` is a lot of punctuation to say very little.
//
// Carried over from the first site, where this list was assembled. It arrived with 🐝 in
// twice — once as "honeybee" and once as "bee" — which the viewer found immediately,
// because it keys its list by the CHARACTER and a repeated key stops the render. A
// character may therefore appear only once per group. That is a strict rule to hold, and
// it is the reason a duplicate cannot sit here unnoticed.

export type EmojiGroup = {
	name: string;
	emojis: [char: string, name: string][];
};

export const EMOJI_GROUPS: EmojiGroup[] = [
	{
		name: 'Smileys & Emotion',
		emojis: [
			['😀', 'grinning face'],
			['😁', 'beaming face'],
			['😂', 'face with tears of joy'],
			['🤣', 'rolling on the floor laughing'],
			['😃', 'grinning face with big eyes'],
			['😄', 'grinning face with smiling eyes'],
			['😅', 'grinning face with sweat'],
			['😆', 'grinning squinting face'],
			['😉', 'winking face'],
			['😊', 'smiling face with smiling eyes'],
			['😋', 'face savoring food'],
			['😎', 'smiling face with sunglasses'],
			['😍', 'smiling face with heart-eyes'],
			['😘', 'face blowing a kiss'],
			['🥰', 'smiling face with hearts'],
			['😗', 'kissing face'],
			['🙂', 'slightly smiling face'],
			['🙃', 'upside-down face'],
			['🫠', 'melting face'],
			['🤗', 'hugging face'],
			['🤩', 'star-struck'],
			['🤔', 'thinking face'],
			['🫡', 'saluting face'],
			['🤨', 'face with raised eyebrow'],
			['😐', 'neutral face'],
			['😑', 'expressionless face'],
			['😶', 'face without mouth'],
			['🙄', 'face with rolling eyes'],
			['😏', 'smirking face'],
			['😣', 'persevering face'],
			['😴', 'sleeping face'],
			['😌', 'relieved face'],
			['😔', 'pensive face'],
			['🤤', 'drooling face'],
			['😪', 'sleepy face'],
			['😷', 'face with medical mask'],
			['🤒', 'face with thermometer'],
			['🤕', 'face with head-bandage'],
			['🤢', 'nauseated face'],
			['🤮', 'face vomiting'],
			['🤧', 'sneezing face'],
			['🥵', 'hot face'],
			['🥶', 'cold face'],
			['🥴', 'woozy face'],
			['😵', 'face with crossed-out eyes'],
			['🤯', 'exploding head'],
			['🥳', 'partying face'],
			['🥸', 'disguised face'],
			['😕', 'confused face'],
			['🫤', 'face with diagonal mouth'],
			['😟', 'worried face'],
			['🙁', 'slightly frowning face'],
			['😮', 'face with open mouth'],
			['😯', 'hushed face'],
			['😲', 'astonished face'],
			['😳', 'flushed face'],
			['🥺', 'pleading face'],
			['🥹', 'face holding back tears'],
			['😦', 'frowning face with open mouth'],
			['😨', 'fearful face'],
			['😰', 'anxious face with sweat'],
			['😥', 'sad but relieved face'],
			['😢', 'crying face'],
			['😭', 'loudly crying face'],
			['😱', 'face screaming in fear'],
			['😖', 'confounded face'],
			['😞', 'disappointed face'],
			['😤', 'face with steam from nose'],
			['😡', 'enraged face'],
			['😠', 'angry face'],
			['🤬', 'face with symbols on mouth'],
			['😈', 'smiling face with horns'],
			['💀', 'skull'],
			['💩', 'pile of poo'],
			['🤡', 'clown face'],
			['👻', 'ghost'],
			['👽', 'alien'],
			['🤖', 'robot'],
			['😺', 'grinning cat'],
			['😸', 'grinning cat with smiling eyes'],
			['😹', 'cat with tears of joy'],
			['💋', 'kiss mark'],
			['❤️', 'red heart'],
			['🧡', 'orange heart'],
			['💛', 'yellow heart'],
			['💚', 'green heart'],
			['💙', 'blue heart'],
			['💜', 'purple heart'],
			['🖤', 'black heart'],
			['🤍', 'white heart'],
			['🤎', 'brown heart'],
			['💔', 'broken heart'],
			['❤️‍🔥', 'heart on fire'],
			['💕', 'two hearts'],
			['💯', 'hundred points'],
			['💢', 'anger symbol'],
			['💨', 'dashing away'],
			['💥', 'collision'],
			['💫', 'dizzy'],
			['💦', 'sweat droplets'],
			['🕳️', 'hole'],
		],
	},
	{
		name: 'People & Gestures',
		emojis: [
			['👋', 'waving hand'],
			['🤚', 'raised back of hand'],
			['🖐️', 'hand with fingers splayed'],
			['✋', 'raised hand'],
			['🖖', 'vulcan salute'],
			['🫱', 'rightwards hand'],
			['🫲', 'leftwards hand'],
			['🫳', 'palm down hand'],
			['🫴', 'palm up hand'],
			['👌', 'OK hand'],
			['🤌', 'pinched fingers'],
			['🤏', 'pinching hand'],
			['✌️', 'victory hand'],
			['🤞', 'crossed fingers'],
			['🫰', 'hand with finger and thumb crossed'],
			['🤟', 'love-you gesture'],
			['🤘', 'sign of the horns'],
			['🤙', 'call me hand'],
			['👈', 'backhand index pointing left'],
			['👉', 'backhand index pointing right'],
			['👆', 'backhand index pointing up'],
			['👇', 'backhand index pointing down'],
			['☝️', 'index pointing up'],
			['👍', 'thumbs up'],
			['👎', 'thumbs down'],
			['✊', 'raised fist'],
			['👊', 'oncoming fist'],
			['🤛', 'left-facing fist'],
			['🤜', 'right-facing fist'],
			['👏', 'clapping hands'],
			['🙌', 'raising hands'],
			['🫶', 'heart hands'],
			['👐', 'open hands'],
			['🤲', 'palms up together'],
			['🤝', 'handshake'],
			['🙏', 'folded hands'],
			['✍️', 'writing hand'],
			['💅', 'nail polish'],
			['🤳', 'selfie'],
			['💪', 'flexed biceps'],
			['🦵', 'leg'],
			['🦶', 'foot'],
			['👂', 'ear'],
			['👃', 'nose'],
			['🧠', 'brain'],
			['🫀', 'anatomical heart'],
			['🦷', 'tooth'],
			['👀', 'eyes'],
			['👁️', 'eye'],
			['👅', 'tongue'],
			['👄', 'mouth'],
			['👶', 'baby'],
			['🧒', 'child'],
			['👦', 'boy'],
			['👧', 'girl'],
			['🧑', 'person'],
			['👨', 'man'],
			['👩', 'woman'],
			['🧓', 'older person'],
			['🙋', 'person raising hand'],
			['🤦', 'person facepalming'],
			['🤷', 'person shrugging'],
			['💁', 'person tipping hand'],
			['🙇', 'person bowing'],
			['🕺', 'man dancing'],
			['💃', 'woman dancing'],
			['🚶', 'person walking'],
			['🏃', 'person running'],
		],
	},
	{
		name: 'Animals & Nature',
		emojis: [
			['🐶', 'dog face'],
			['🐱', 'cat face'],
			['🐭', 'mouse face'],
			['🐹', 'hamster'],
			['🐰', 'rabbit face'],
			['🦊', 'fox'],
			['🐻', 'bear'],
			['🐼', 'panda'],
			['🐨', 'koala'],
			['🐯', 'tiger face'],
			['🦁', 'lion'],
			['🐮', 'cow face'],
			['🐷', 'pig face'],
			['🐸', 'frog'],
			['🐵', 'monkey face'],
			['🙈', 'see-no-evil monkey'],
			['🐔', 'chicken'],
			['🐧', 'penguin'],
			['🐦', 'bird'],
			['🐤', 'baby chick'],
			['🦆', 'duck'],
			['🦅', 'eagle'],
			['🦉', 'owl'],
			['🦇', 'bat'],
			['🐺', 'wolf'],
			['🐗', 'boar'],
			['🐴', 'horse face'],
			['🦄', 'unicorn'],
			['🐝', 'honeybee'],
			['🪲', 'beetle'],
			['🐛', 'bug'],
			['🦋', 'butterfly'],
			['🐌', 'snail'],
			['🐞', 'lady beetle'],
			['🐜', 'ant'],
			['🕷️', 'spider'],
			['🦂', 'scorpion'],
			['🐢', 'turtle'],
			['🐍', 'snake'],
			['🦖', 'T-Rex'],
			['🐙', 'octopus'],
			['🦑', 'squid'],
			['🦐', 'shrimp'],
			['🦀', 'crab'],
			['🐡', 'blowfish'],
			['🐠', 'tropical fish'],
			['🐟', 'fish'],
			['🐬', 'dolphin'],
			['🐳', 'spouting whale'],
			['🦈', 'shark'],
			['🐊', 'crocodile'],
			['🐅', 'tiger'],
			['🐘', 'elephant'],
			['🦏', 'rhinoceros'],
			['🦛', 'hippopotamus'],
			['🐪', 'camel'],
			['🦒', 'giraffe'],
			['🦘', 'kangaroo'],
			['🐇', 'rabbit'],
			['🦔', 'hedgehog'],
			['🐿️', 'chipmunk'],
			['🦫', 'beaver'],
			['🐓', 'rooster'],
			['🦚', 'peacock'],
			['🦜', 'parrot'],
			['🌵', 'cactus'],
			['🎄', 'Christmas tree'],
			['🌲', 'evergreen tree'],
			['🌳', 'deciduous tree'],
			['🌴', 'palm tree'],
			['🌱', 'seedling'],
			['🌿', 'herb'],
			['☘️', 'shamrock'],
			['🍀', 'four leaf clover'],
			['🍁', 'maple leaf'],
			['🍄', 'mushroom'],
			['🌾', 'sheaf of rice'],
			['💐', 'bouquet'],
			['🌷', 'tulip'],
			['🌹', 'rose'],
			['🌺', 'hibiscus'],
			['🌸', 'cherry blossom'],
			['🌼', 'blossom'],
			['🌻', 'sunflower'],
			['🌞', 'sun with face'],
			['🌝', 'full moon face'],
			['🌚', 'new moon face'],
			['🌙', 'crescent moon'],
			['⭐', 'star'],
			['🌟', 'glowing star'],
			['✨', 'sparkles'],
			['⚡', 'high voltage'],
			['🔥', 'fire'],
			['🌈', 'rainbow'],
			['☀️', 'sun'],
			['⛅', 'sun behind cloud'],
			['☁️', 'cloud'],
			['🌧️', 'cloud with rain'],
			['⛄', 'snowman'],
			['❄️', 'snowflake'],
			['💧', 'droplet'],
			['🌊', 'water wave'],
		],
	},
	{
		name: 'Food & Drink',
		emojis: [
			['🍏', 'green apple'],
			['🍎', 'red apple'],
			['🍐', 'pear'],
			['🍊', 'tangerine'],
			['🍋', 'lemon'],
			['🍌', 'banana'],
			['🍉', 'watermelon'],
			['🍇', 'grapes'],
			['🍓', 'strawberry'],
			['🫐', 'blueberries'],
			['🍈', 'melon'],
			['🍒', 'cherries'],
			['🍑', 'peach'],
			['🥭', 'mango'],
			['🍍', 'pineapple'],
			['🥥', 'coconut'],
			['🥝', 'kiwi fruit'],
			['🍅', 'tomato'],
			['🍆', 'eggplant'],
			['🥑', 'avocado'],
			['🥦', 'broccoli'],
			['🥬', 'leafy green'],
			['🥒', 'cucumber'],
			['🌶️', 'hot pepper'],
			['🌽', 'ear of corn'],
			['🥕', 'carrot'],
			['🧄', 'garlic'],
			['🧅', 'onion'],
			['🥔', 'potato'],
			['🍠', 'roasted sweet potato'],
			['🥐', 'croissant'],
			['🥯', 'bagel'],
			['🍞', 'bread'],
			['🥖', 'baguette bread'],
			['🥨', 'pretzel'],
			['🧀', 'cheese wedge'],
			['🥚', 'egg'],
			['🍳', 'cooking'],
			['🧇', 'waffle'],
			['🥞', 'pancakes'],
			['🥓', 'bacon'],
			['🍔', 'hamburger'],
			['🍟', 'french fries'],
			['🍕', 'pizza'],
			['🌭', 'hot dog'],
			['🥪', 'sandwich'],
			['🌮', 'taco'],
			['🌯', 'burrito'],
			['🥙', 'stuffed flatbread'],
			['🧆', 'falafel'],
			['🍝', 'spaghetti'],
			['🍜', 'steaming bowl'],
			['🍲', 'pot of food'],
			['🍛', 'curry rice'],
			['🍣', 'sushi'],
			['🍱', 'bento box'],
			['🥟', 'dumpling'],
			['🍤', 'fried shrimp'],
			['🍙', 'rice ball'],
			['🍚', 'cooked rice'],
			['🍥', 'fish cake with swirl'],
			['🥠', 'fortune cookie'],
			['🍦', 'soft ice cream'],
			['🍧', 'shaved ice'],
			['🍨', 'ice cream'],
			['🍩', 'doughnut'],
			['🍪', 'cookie'],
			['🎂', 'birthday cake'],
			['🍰', 'shortcake'],
			['🧁', 'cupcake'],
			['🥧', 'pie'],
			['🍫', 'chocolate bar'],
			['🍬', 'candy'],
			['🍭', 'lollipop'],
			['🍮', 'custard'],
			['🍯', 'honey pot'],
			['🍼', 'baby bottle'],
			['🥛', 'glass of milk'],
			['☕', 'hot beverage'],
			['🍵', 'teacup without handle'],
			['🧃', 'beverage box'],
			['🥤', 'cup with straw'],
			['🍶', 'sake'],
			['🍺', 'beer mug'],
			['🍻', 'clinking beer mugs'],
			['🥂', 'clinking glasses'],
			['🍷', 'wine glass'],
			['🥃', 'tumbler glass'],
			['🍸', 'cocktail glass'],
			['🍹', 'tropical drink'],
			['🧉', 'mate'],
			['🍾', 'bottle with popping cork'],
			['🧊', 'ice'],
			['🥄', 'spoon'],
			['🍴', 'fork and knife'],
			['🍽️', 'fork and knife with plate'],
			['🧂', 'salt'],
		],
	},
	{
		name: 'Travel & Places',
		emojis: [
			['🚗', 'automobile'],
			['🚕', 'taxi'],
			['🚙', 'sport utility vehicle'],
			['🚌', 'bus'],
			['🏎️', 'racing car'],
			['🚓', 'police car'],
			['🚑', 'ambulance'],
			['🚒', 'fire engine'],
			['🚚', 'delivery truck'],
			['🚜', 'tractor'],
			['🛵', 'motor scooter'],
			['🏍️', 'motorcycle'],
			['🚲', 'bicycle'],
			['🛴', 'kick scooter'],
			['🚂', 'locomotive'],
			['🚄', 'high-speed train'],
			['🚈', 'light rail'],
			['🚇', 'metro'],
			['🚉', 'station'],
			['✈️', 'airplane'],
			['🛫', 'airplane departure'],
			['🛬', 'airplane arrival'],
			['🚁', 'helicopter'],
			['🚀', 'rocket'],
			['🛸', 'flying saucer'],
			['⛵', 'sailboat'],
			['🚤', 'speedboat'],
			['🛳️', 'passenger ship'],
			['⚓', 'anchor'],
			['🚧', 'construction'],
			['⛽', 'fuel pump'],
			['🚦', 'vertical traffic light'],
			['🗺️', 'world map'],
			['🧭', 'compass'],
			['🏔️', 'snow-capped mountain'],
			['⛰️', 'mountain'],
			['🌋', 'volcano'],
			['🏕️', 'camping'],
			['🏖️', 'beach with umbrella'],
			['🏜️', 'desert'],
			['🏝️', 'desert island'],
			['🏞️', 'national park'],
			['🏟️', 'stadium'],
			['🏛️', 'classical building'],
			['🏗️', 'building construction'],
			['🏠', 'house'],
			['🏡', 'house with garden'],
			['🏢', 'office building'],
			['🏣', 'Japanese post office'],
			['🏥', 'hospital'],
			['🏦', 'bank'],
			['🏨', 'hotel'],
			['🏪', 'convenience store'],
			['🏫', 'school'],
			['🏬', 'department store'],
			['🏭', 'factory'],
			['🏰', 'castle'],
			['💒', 'wedding'],
			['🗼', 'Tokyo tower'],
			['🗽', 'Statue of Liberty'],
			['⛩️', 'shinto shrine'],
			['🕌', 'mosque'],
			['⛪', 'church'],
			['🏙️', 'cityscape'],
			['🌆', 'cityscape at dusk'],
			['🌃', 'night with stars'],
			['🌉', 'bridge at night'],
			['🌁', 'foggy'],
		],
	},
	{
		name: 'Activities',
		emojis: [
			['⚽', 'soccer ball'],
			['🏀', 'basketball'],
			['🏈', 'american football'],
			['⚾', 'baseball'],
			['🥎', 'softball'],
			['🎾', 'tennis'],
			['🏐', 'volleyball'],
			['🏉', 'rugby football'],
			['🥏', 'flying disc'],
			['🎱', 'pool 8 ball'],
			['🏓', 'ping pong'],
			['🏸', 'badminton'],
			['🥅', 'goal net'],
			['🏒', 'ice hockey'],
			['🥍', 'lacrosse'],
			['🏏', 'cricket game'],
			['⛳', 'flag in hole'],
			['🏹', 'bow and arrow'],
			['🎣', 'fishing pole'],
			['🥊', 'boxing glove'],
			['🥋', 'martial arts uniform'],
			['⛸️', 'ice skate'],
			['🛼', 'roller skate'],
			['🛹', 'skateboard'],
			['🛷', 'sled'],
			['🎿', 'skis'],
			['🏂', 'snowboarder'],
			['🏋️', 'person lifting weights'],
			['🤸', 'person cartwheeling'],
			['🤾', 'person playing handball'],
			['🏌️', 'person golfing'],
			['🏄', 'person surfing'],
			['🏊', 'person swimming'],
			['🚴', 'person biking'],
			['🧗', 'person climbing'],
			['🎽', 'running shirt'],
			['🏅', 'sports medal'],
			['🥇', '1st place medal'],
			['🥈', '2nd place medal'],
			['🥉', '3rd place medal'],
			['🏆', 'trophy'],
			['🎯', 'bullseye'],
			['🎮', 'video game'],
			['🕹️', 'joystick'],
			['🎰', 'slot machine'],
			['🎲', 'game die'],
			['🧩', 'puzzle piece'],
			['♟️', 'chess pawn'],
			['🎨', 'artist palette'],
			['🎭', 'performing arts'],
			['🎬', 'clapper board'],
			['🎤', 'microphone'],
			['🎧', 'headphone'],
			['🎼', 'musical score'],
			['🎹', 'musical keyboard'],
			['🥁', 'drum'],
			['🎷', 'saxophone'],
			['🎺', 'trumpet'],
			['🎸', 'guitar'],
			['🎻', 'violin'],
			['🪕', 'banjo'],
			['🎪', 'circus tent'],
			['🎟️', 'admission tickets'],
			['🎉', 'party popper'],
			['🎊', 'confetti ball'],
			['🎈', 'balloon'],
			['🎁', 'wrapped gift'],
			['🎃', 'jack-o-lantern'],
			['🎆', 'fireworks'],
		],
	},
	{
		name: 'Objects',
		emojis: [
			['⌚', 'watch'],
			['📱', 'mobile phone'],
			['💻', 'laptop'],
			['⌨️', 'keyboard'],
			['🖥️', 'desktop computer'],
			['🖨️', 'printer'],
			['🖱️', 'computer mouse'],
			['💽', 'computer disk'],
			['💾', 'floppy disk'],
			['💿', 'optical disk'],
			['📷', 'camera'],
			['📸', 'camera with flash'],
			['📹', 'video camera'],
			['🎥', 'movie camera'],
			['📞', 'telephone receiver'],
			['📟', 'pager'],
			['📺', 'television'],
			['📻', 'radio'],
			['🎙️', 'studio microphone'],
			['⏱️', 'stopwatch'],
			['⏰', 'alarm clock'],
			['🕰️', 'mantelpiece clock'],
			['🔋', 'battery'],
			['🔌', 'electric plug'],
			['💡', 'light bulb'],
			['🔦', 'flashlight'],
			['🕯️', 'candle'],
			['🪫', 'low battery'],
			['💰', 'money bag'],
			['💳', 'credit card'],
			['💎', 'gem stone'],
			['⚖️', 'balance scale'],
			['🧰', 'toolbox'],
			['🔧', 'wrench'],
			['🔨', 'hammer'],
			['⚙️', 'gear'],
			['🧱', 'brick'],
			['🔗', 'link'],
			['⛓️', 'chains'],
			['🧲', 'magnet'],
			['🔫', 'water pistol'],
			['💣', 'bomb'],
			['🧨', 'firecracker'],
			['🔪', 'kitchen knife'],
			['🗡️', 'dagger'],
			['🛡️', 'shield'],
			['🚬', 'cigarette'],
			['⚰️', 'coffin'],
			['🏺', 'amphora'],
			['🔮', 'crystal ball'],
			['🧿', 'nazar amulet'],
			['💊', 'pill'],
			['💉', 'syringe'],
			['🩹', 'adhesive bandage'],
			['🩺', 'stethoscope'],
			['🌡️', 'thermometer'],
			['🧬', 'dna'],
			['🔬', 'microscope'],
			['🔭', 'telescope'],
			['📡', 'satellite antenna'],
			['🧴', 'lotion bottle'],
			['🧼', 'soap'],
			['🧽', 'sponge'],
			['🧹', 'broom'],
			['🪣', 'bucket'],
			['🛒', 'shopping cart'],
			['🔑', 'key'],
			['🗝️', 'old key'],
			['🚪', 'door'],
			['🛋️', 'couch and lamp'],
			['🛏️', 'bed'],
			['🚽', 'toilet'],
			['🚿', 'shower'],
			['🛁', 'bathtub'],
			['📖', 'open book'],
			['📚', 'books'],
			['📓', 'notebook'],
			['📄', 'page facing up'],
			['📰', 'newspaper'],
			['📌', 'pushpin'],
			['📎', 'paperclip'],
			['✂️', 'scissors'],
			['📐', 'triangular ruler'],
			['📏', 'straight ruler'],
			['✏️', 'pencil'],
			['🖊️', 'pen'],
			['🖌️', 'paintbrush'],
			['🖍️', 'crayon'],
			['📝', 'memo'],
			['💼', 'briefcase'],
			['📅', 'calendar'],
			['📆', 'tear-off calendar'],
			['📇', 'card index'],
			['📈', 'chart increasing'],
			['📉', 'chart decreasing'],
			['📊', 'bar chart'],
			['📋', 'clipboard'],
			['📁', 'file folder'],
			['🗂️', 'card index dividers'],
			['🗑️', 'wastebasket'],
			['🔒', 'locked'],
			['🔓', 'unlocked'],
			['💌', 'love letter'],
			['📧', 'e-mail'],
			['📦', 'package'],
			['📫', 'closed mailbox with raised flag'],
			['⏳', 'hourglass not done'],
			['⌛', 'hourglass done'],
		],
	},
	{
		name: 'Symbols',
		emojis: [
			['❤️', 'red heart'],
			['✅', 'check mark button'],
			['❌', 'cross mark'],
			['❎', 'cross mark button'],
			['➕', 'plus'],
			['➖', 'minus'],
			['➗', 'divide'],
			['✖️', 'multiply'],
			['♾️', 'infinity'],
			['‼️', 'double exclamation mark'],
			['⁉️', 'exclamation question mark'],
			['❓', 'question mark'],
			['❔', 'white question mark'],
			['❗', 'exclamation mark'],
			['〰️', 'wavy dash'],
			['💱', 'currency exchange'],
			['💲', 'heavy dollar sign'],
			['⚕️', 'medical symbol'],
			['♻️', 'recycling symbol'],
			['⚜️', 'fleur-de-lis'],
			['🔱', 'trident emblem'],
			['📛', 'name badge'],
			['🔰', 'Japanese symbol for beginner'],
			['⭕', 'hollow red circle'],
			['✳️', 'eight-spoked asterisk'],
			['✴️', 'eight-pointed star'],
			['❇️', 'sparkle'],
			['©️', 'copyright'],
			['®️', 'registered'],
			['™️', 'trade mark'],
			['#️⃣', 'keycap number sign'],
			['*️⃣', 'keycap asterisk'],
			['0️⃣', 'keycap 0'],
			['1️⃣', 'keycap 1'],
			['2️⃣', 'keycap 2'],
			['🔟', 'keycap 10'],
			['🔠', 'input latin uppercase'],
			['🔡', 'input latin lowercase'],
			['🔢', 'input numbers'],
			['🔣', 'input symbols'],
			['🔤', 'input latin letters'],
			['🅰️', 'A button'],
			['🆎', 'AB button'],
			['🆑', 'CL button'],
			['🆒', 'COOL button'],
			['🆓', 'FREE button'],
			['ℹ️', 'information'],
			['🆕', 'NEW button'],
			['🆗', 'OK button'],
			['🅾️', 'O button'],
			['🆘', 'SOS button'],
			['🚫', 'prohibited'],
			['📵', 'no mobile phones'],
			['🔞', 'no one under eighteen'],
			['⚠️', 'warning'],
			['🚸', 'children crossing'],
			['♿', 'wheelchair symbol'],
			['🚭', 'no smoking'],
			['🔃', 'clockwise vertical arrows'],
			['🔄', 'counterclockwise arrows'],
			['🔙', 'back arrow'],
			['🔚', 'end arrow'],
			['🔛', 'on arrow'],
			['🔝', 'top arrow'],
			['🔜', 'soon arrow'],
			['✔️', 'check mark'],
			['☑️', 'check box with check'],
			['🔘', 'radio button'],
			['⚪', 'white circle'],
			['⚫', 'black circle'],
			['🔴', 'red circle'],
			['🟠', 'orange circle'],
			['🟡', 'yellow circle'],
			['🟢', 'green circle'],
			['🔵', 'blue circle'],
			['🟣', 'purple circle'],
			['🟤', 'brown circle'],
			['🔺', 'red triangle pointed up'],
			['🔻', 'red triangle pointed down'],
			['💠', 'diamond with a dot'],
			['🔷', 'large blue diamond'],
			['🔶', 'large orange diamond'],
			['♠️', 'spade suit'],
			['♥️', 'heart suit'],
			['♦️', 'diamond suit'],
			['♣️', 'club suit'],
			['🃏', 'joker'],
			['🀄', 'mahjong red dragon'],
			['🕐', 'one o’clock'],
			['🔀', 'shuffle tracks button'],
			['🔁', 'repeat button'],
			['▶️', 'play button'],
			['⏸️', 'pause button'],
			['⏹️', 'stop button'],
			['⏭️', 'next track button'],
			['🔼', 'upwards button'],
			['🔽', 'downwards button'],
			['🔅', 'dim button'],
			['🔆', 'bright button'],
			['📶', 'antenna bars'],
			['🔇', 'muted speaker'],
			['🔊', 'speaker high volume'],
			['🔔', 'bell'],
			['🔕', 'bell with slash'],
		],
	},
	{
		name: 'Flags',
		emojis: [
			['🏳️', 'white flag'],
			['🏴', 'black flag'],
			['🏁', 'chequered flag'],
			['🚩', 'triangular flag'],
			['🏳️‍🌈', 'rainbow flag'],
			['🏴‍☠️', 'pirate flag'],
			['🇺🇸', 'United States'],
			['🇨🇦', 'Canada'],
			['🇲🇽', 'Mexico'],
			['🇬🇧', 'United Kingdom'],
			['🇮🇪', 'Ireland'],
			['🇫🇷', 'France'],
			['🇩🇪', 'Germany'],
			['🇪🇸', 'Spain'],
			['🇮🇹', 'Italy'],
			['🇵🇹', 'Portugal'],
			['🇳🇱', 'Netherlands'],
			['🇧🇪', 'Belgium'],
			['🇨🇭', 'Switzerland'],
			['🇦🇹', 'Austria'],
			['🇸🇪', 'Sweden'],
			['🇳🇴', 'Norway'],
			['🇩🇰', 'Denmark'],
			['🇫🇮', 'Finland'],
			['🇵🇱', 'Poland'],
			['🇷🇺', 'Russia'],
			['🇺🇦', 'Ukraine'],
			['🇬🇷', 'Greece'],
			['🇹🇷', 'Turkey'],
			['🇯🇵', 'Japan'],
			['🇰🇷', 'South Korea'],
			['🇨🇳', 'China'],
			['🇹🇼', 'Taiwan'],
			['🇭🇰', 'Hong Kong'],
			['🇻🇳', 'Vietnam'],
			['🇹🇭', 'Thailand'],
			['🇵🇭', 'Philippines'],
			['🇮🇩', 'Indonesia'],
			['🇮🇳', 'India'],
			['🇸🇬', 'Singapore'],
			['🇦🇺', 'Australia'],
			['🇳🇿', 'New Zealand'],
			['🇧🇷', 'Brazil'],
			['🇦🇷', 'Argentina'],
			['🇨🇱', 'Chile'],
			['🇨🇴', 'Colombia'],
			['🇵🇪', 'Peru'],
			['🇪🇬', 'Egypt'],
			['🇿🇦', 'South Africa'],
			['🇳🇬', 'Nigeria'],
			['🇰🇪', 'Kenya'],
			['🇮🇱', 'Israel'],
			['🇸🇦', 'Saudi Arabia'],
			['🇦🇪', 'United Arab Emirates'],
		],
	},
];
